environment: development
base_dir: /home/dlink/landis
base_url: http://dev.crowfly.net/landis

database:
   engine: mysql
   host  : localhost
   user  : landis
   passwd: REDmondrian5
   db    : landis
   dictcursor: True

email:
   server  : smtp.gmail.com:587
   username: username
   password: password
   fromaddr: Landis Refining customerservice@LandisRefining.com


